name ; CI 

## when this run: on pushes and PRs to main

on: 
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs: 
    ### -- job 1: run the test --
        test:
            runs-on: ubuntu-latest
            defaults:
                run:
                    working-directory: RAG-QA
            steps: 
                - uses: actiona/checkout@v4
                - uses: actions/setup-python@v4
                  with:
                      python-version: "3.12"
                - name: Install dependencies
                  run: | 
                    pip install --timeout=1000 -- retries=10 torch --index-url https://download.pytorch.org/whl/cpu
                    pip install --timeout=1000 --retries=10 -r requirements.txt
                - name: Run tests
                  run: pystest -v 

    
### job 2 : build the docker image(only if tests pass)
build: 
    runs-on: ubuntu-latest
    needs: test
    steps:
        - uses: actions/checkout@v4

        - name: Build Docker image 
          run: docker build -t rag-qa RAG-QA 

        # Start the image as a container in the background 
        - name: Run the Container 
          run: docker run -d -p 8000:8000 --name rag rag-qa


        # POLL /HEALTH until it responds( or fail after 30 seconds)
        - name : Ping /health
        run : | 
            for i in $(seq 1 15); do
                if curl -fs http://localhost:8000/health; then
                    echo "Health check passed!"
                    exit 0
                fi 
                echo " waiting for container.. ($i)"
                sleep 2 
            done 
            echo " Health Check failed - container logs:"
            docker logs rag
            exit 1

        # clean up
        - name: Stop the container
          if : always()
          run : docker rm -f rag
          